# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11shCsmKSccl8EJJkdMO8CqW94lsZoeHc
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)
def load_dataset(path):
    data = pd.read_csv(path)
    return data
def split_features_labels(data):
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]
    return X, y
def train_knn(X_train, y_train, k):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    return model
def evaluate_model(model, X, y):
    y_pred = model.predict(X)
    cm = confusion_matrix(y, y_pred)
    precision = precision_score(y, y_pred, average='weighted')
    recall = recall_score(y, y_pred, average='weighted')
    f1 = f1_score(y, y_pred, average='weighted')
    return cm, precision, recall, f1
def tune_k_value(X_train, y_train):
    param_grid = {'n_neighbors': np.arange(1, 21)}
    knn = KNeighborsClassifier()
    grid = GridSearchCV(knn, param_grid, cv=5, scoring='f1_weighted')
    grid.fit(X_train, y_train)
    return grid.best_params_, grid.best_score_
dataset = load_dataset("DCT_mal.csv")
X, y = split_features_labels(dataset)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
k = 3
knn_model = train_knn(X_train, y_train, k)
cm_train, p_train, r_train, f1_train = evaluate_model(
    knn_model, X_train, y_train
)
cm_test, p_test, r_test, f1_test = evaluate_model(
    knn_model, X_test, y_test
)
print("=== TRAINING PERFORMANCE ===")
print("Confusion Matrix:\n", cm_train)
print("Precision:", p_train)
print("Recall:", r_train)
print("F1 Score:", f1_train)

print("\n=== TEST PERFORMANCE ===")
print("Confusion Matrix:\n", cm_test)
print("Precision:", p_test)
print("Recall:", r_test)
print("F1 Score:", f1_test)
best_k, best_score = tune_k_value(X_train, y_train)

print("\n=== HYPERPARAMETER TUNING ===")
print("Best k value:", best_k['n_neighbors'])
print("Best CV F1 Score:", best_score)