# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiY2-YqE4bm8ffJR1XABg3oA7cLFehMf
"""

import numpy as np
A = [1, 2, 3]
B = [4, 5, 6]
def dot_product(A, B):
    result = 0
    for i in range(len(A)):
        result += A[i] * B[i]
    return result
def euclidean_norm(V):
    sum_sq = 0
    for x in V:
        sum_sq += x * x
    return sum_sq ** 0.5

own_dot = dot_product(A, B)
own_norm_A = euclidean_norm(A)
own_norm_B = euclidean_norm(B)

np_dot = np.dot(A, B)
np_norm_A = np.linalg.norm(A)
np_norm_B = np.linalg.norm(B)

print("Own Dot Product:", own_dot)
print("NumPy Dot Product:", np_dot)

print("\nOwn Euclidean Norm of A:", own_norm_A)
print("NumPy Norm of A:", np_norm_A)

print("\nOwn Euclidean Norm of B:", own_norm_B)
print("NumPy Norm of B:", np_norm_B)



